[build-system]
requires = ["setuptools==80.7.1"]
build-backend = "setuptools.build_meta"

[project]
name = "interpretable-splade-classifier"
version = "1.0.0"
dependencies = [
    "captum==0.8.0",
    "datasets==4.5.0",
    "lime==0.2.0.1",
    "nltk==3.9.1",
    "numpy==1.26.4",
    "scikit-learn>=1.3.0",
    "scipy>=1.11.0",
    "torch==2.9.1",
    "tqdm==4.67.1",
    "transformers==4.57.6",
    "pyyaml",
]
